version: "2"

services:
  sniproxy:
    build:
      context: ./
      dockerfile: Dockerfile-sniproxy
    image: alpine-sniproxy:local
    container_name: sniproxy
    dns: 172.16.62.3  #Not showed in resolv.conf but still used!
    networks:
      sniproxy_vlan:
        aliases:
          - sniproxy
        ipv4_address: 172.16.62.2
    restart: always
    depends_on:
      - sniproxy-dnsmasq

  sniproxy-dnsmasq:
    build:
      context: ./
      dockerfile: Dockerfile-dnsmasq
    image: alpine-dnsmasq:local
    container_name: sniproxy-dnsmasq
    privileged: true
    networks:
      sniproxy_vlan:
        aliases:
          - dnsmasq
        ipv4_address: 172.16.62.3
    restart: always

networks:
  sniproxy_vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0.62
    ipam:
      config:
        - subnet: 172.16.62.0/29
          gateway: 172.16.62.1
